### PR TITLE
Item View Updates

### PR DESCRIPTION
**Pull request by respinos**
- download menu is more articulate about the type of download
- just use a download button if there's only one file available
- re-arrange technical and record metadata
- technical metadata handles non-image assets
- adjust the blank cell to handle different not-an-image types

To preview:

Open: https://dcp-proto.kubernetes.lib.umich.edu/samples/

<strike>Click the "transforms" button in the bottom corner - this sets a cookie for the proxy to route to `beta1`, which is where the on-server development is happening. When `beta1` is active this button has a green border (sorry, rushing)</strike> This was a cool idea, but the `beta1` static resources can't be accessed off-campus and that was one hack too many for the evening 🤯 

If you use the Library VPN (because UM VPN != campus):

- [image item view](https://beta1.quod.lib.umich.edu/c/clark1ic/x-005247144/39015095421411_0001) should show "Download Image"
- [document item view](https://beta1.quod.lib.umich.edu/b/bp1ic/x-cn23/KLINEDOBLTR.DOC?lastview=reslist;resnum=38;size=50;subview=detail;view=entry;rgn1=ic_all;q1=bp1ic) should show "Download PDF"
- [reslist showing audio thumbnails](https://beta1.quod.lib.umich.edu/a/amph2ic?view=reslist;q1=amph2ic)

### CODE REVIEW

**Review by bridgetburke — COMMENTED** [review]
- Buttons looks great! The dropdown menu works great with keyboard. The teal mouse hover is nice.
- Download icon is different sizes for Dropdown vs single.
- Noticed the full citation is the full page width and overlaps the page index if scrolled to the bottom at around 1300px width.

**Comment by respinos** [comment]
> * Download icon is different sizes for Dropdown vs single.

Do you recall what size the viewport was? The dropdown has a `<span>` inside the shoelace component styled to `1rem` via `style`, which is what the other icons should be styled as in the CSS.

> * Noticed the full citation is the full page width and overlaps the page index if scrolled to the bottom at around 1300px width.

...and I noticed that if the bookmark URL has a `%` in it, the full citation is just broken. (So always beta1? So odd!)

**Comment by bridgetburke** [comment]
> > * Download icon is different sizes for Dropdown vs single.
> 
> Do you recall what size the viewport was? The dropdown has a `<span>` inside the shoelace component styled to `1rem` via `style`, which is what the other icons should be styled as in the CSS.
> 

I'm on my 13.3 MacBook, so most likely between 1280 and 1440px for the viewport.

**Comment by respinos** [comment]
OK. Worked around the weird issue with the full citation and XML::LibXSLT (vs. xsltproc in dcp-proto). And actually added the `font-size` on the icon in the dropdown instead of just thinking there was one.

**Comment by bridgetburke** [comment]
> OK. Worked around the weird issue with the full citation and XML::LibXSLT (vs. xsltproc in dcp-proto). And actually added the `font-size` on the icon in the dropdown instead of just thinking there was one.

Looks awesome!!

**Review by bridgetburke — APPROVED** [review]

**Pull request merged**
